export const GET_TASKS_REQUEST = 'GETTING_TASKS';
export const GET_TASKS_SUCCESS='GET_TASKS_SUCCESS'
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';


export const ADD_TASK_REQUEST = 'ADDING_TASK';
export const ADD_TASK_SUCCESS='ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const EDIT_TASKS_REQUEST='EDITING_TASKS';
export const EDIT_TASK_SUCCESS='EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE='EDIT_TASK_FAILURE';
