export const GET_TASKS_REQUEST = 'GETTING_TASKS';
export const GET_TASKS_SUCCESS='GET_TASKS_SUCCESS'
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';

export const ADD_TASK_REQUEST = 'ADDING_TASK';
export const ADD_TASK_SUCCESS='ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const EDIT_TASKS_REQUEST='EDITING_TASKS';
export const EDIT_TASK_SUCCESS='EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE='EDIT_TASK_FAILURE';

export const DEL_TASK_REQUEST='DELING_TASK';
export const DEL_TASK_SUCCESS='DEL_TASK_SUCCESS';
export const DEL_TASK_FAILURE='DEL_TASK_FAILURE';

export const DEL_BULK_REQUEST='DELING_BULK_TASKS';
export const DEL_BULK_SUCCESS='DEL_BULK_SUCCESS';
export const DEL_BULK_FAILURE='DEL_BULK_FAILURE';

export const CONTACT_REQUEST='CONTACT_REQUES';
export const CONTACT_SUCCESS='CONTACT_SUCCESS';
export const CONTACT_FAILURE='CONTACT_FAILURE';

export const SINGLETASK_REQUEST='SINGLETASK_REQUES';
export const SINGLETASK_SUCCESS='SINGLETASK_SUCCESS';
export const SINGLETASK_FAILURE='SINGLETASK_FAILURE';

export const SEARCH_REQUEST='SEARCH_REQUES';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FAILURE='SEARCH_FAILURE';

export const EDIT_SINGLETASKS_REQUEST='EDIT_SINGLETASKS_REQUEST';
export const EDIT_SINGLETASK_SUCCESS='EDIT_SINGLETASK_SUCCESS';
export const EDIT_SINGLETASK_FAILURE='EDIT_SINGLETASK_FAILURE';
